repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.9
    hooks:
      - id: check-model-has-description
        args:
          - --manifest
          - dbt_dagster_pipeline/target/manifest.json