name: Dev Testing & Auto-Merge

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  dbt-ci-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Execute dbt Validation
        env:
          DBT_PROFILES_DIR: .
          DB_PASSWORD: ${{ secrets.DB_DEV_PASSWORD }}
        run: |
          uv run dbt deps
          uv run dbt debug
          uv run dbt build

      - name: Auto Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch